name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  linters-checking:
    name: Check JS lint and syntax
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          npm install
      - name: Check JS lint
        run: npm run lint
